config/routes.rb
Rails.application.routes.draw do
  resources :charges
  root to: 'charges#index'
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :customer

  scope :failed, -> { where(paid: false) }
  scope :disputed, -> { where(refunded: true) }
  scope :successed, -> { where(paid: true, refunded: false) }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :charges

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:paid, :amount, :currency, :refunded, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_charges_table.html.haml
%table
  %tr
    %th Customer
    %th Amount
    %th Date
  - charges.each do |charge|
    %tr.charge-row-value
      %td= charge.customer.full_name
      %td= charge.amount
      %td= DateTime.strptime(charge.created.to_s,'%s')

app/views/charges/_form.html.haml
= form_for @charge do |f|
  - if @charge.errors.any?
    #error_explanation
      %h2= "#{pluralize(@charge.errors.count, "error")} prohibited this charge from being saved:"
      %ul
        - @charge.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :paid
    = f.check_box :paid
  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :currency
    = f.text_field :currency
  .field
    = f.label :refunded
    = f.check_box :refunded
  .field
    = f.label :customer_id
    = f.number_field :customer_id
  .actions
    = f.submit 'Save'

app/views/charges/edit.html.haml
%h1 Editing charge

= render 'form'

= link_to 'Show', @charge
\|
= link_to 'Back', charges_path

app/views/charges/index.html.haml
.charge-table.failed
  %h1 Failed Charges
  = render partial: 'charges_table',  locals: { charges: @charges.failed }

.charge-table.disputed
  %h1 Disputed Charges
  = render partial: 'charges_table',  locals: { charges: @charges.disputed }

.charge-table.successful
  %h1 Successful Charges
  = render partial: 'charges_table',  locals: { charges: @charges.successed }

app/views/charges/new.html.haml
%h1 New charge

= render 'form'

= link_to 'Back', charges_path

app/views/charges/show.html.haml
%p#notice= notice

%p
  %b Paid:
  = @charge.paid
%p
  %b Amount:
  = @charge.amount
%p
  %b Currency:
  = @charge.currency
%p
  %b Refunded:
  = @charge.refunded
%p
  %b Customer:
  = @charge.customer_id

= link_to 'Edit', edit_charge_path(@charge)
\|
= link_to 'Back', charges_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ExampleRailsChallenge
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield